### PR TITLE
HTTPS_SUPPORT

### PR DESCRIPTION
**Pull request by ptillemans**
When injecting in https page, modern browsers refuse to load from http
addresses.

This patch changes the proxy server to use https and adds support to
proxy https requests in addition to http requests.

The https server expects a key and a certificate in
~/.swankjs/swankjs.key resp ~/.swankjs/swankjs.crt.

### CODE REVIEW

**Comment by MC-Escherichia** [comment]
Thanks for the PR. I've accepted and added documentation to the README

**Comment by MC-Escherichia** [comment]
@ptillemans , How do you generate your keypair? I keep getting an error about 'bad password read' when I try to use this branch, and I can't figure out how to generate a keypair using openssh without inputing a password.

**Comment by ptillemans** [comment]
I use a tool to manage certificates for my small organization. However this is straightforward to do with openssl.

openssl req -x509 -newkey rsa:2048 -keyout swankjs.key -out swankjs.crt -days 999
Generating a 2048 bit RSA private key
.......................................................+++
..................................................+++
writing new private key to 'swankjs.key'
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
phrase is too short, needs to be at least 4 chars
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
phrase is too short, needs to be at least 4 chars
Enter PEM pass phrase:

## Verifying - Enter PEM pass phrase:

You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,

## If you enter '.', the field will be left blank.

Country Name (2 letter code) [AU]:BE
State or Province Name (full name) [Some-State]:Antwerpen
Locality Name (eg, city) []:Antwerpen
Organization Name (eg, company) [Internet Widgits Pty Ltd]:Snamellit bvba
Organizational Unit Name (eg, section) []:it
Common Name (e.g. server FQDN or YOUR name) []:localhost
Email Address []:

the common name must be localhost if that is the hostname you use to connect to from your browser.

Now you need to import the swankjs.crt file in your browser as a trusted certificate. This differs from browser to browser and version to version. It boils down to going to the proxy url, getting a warning/error and confirming that this certificate is Ok. I have to google this each time too.

**Comment by synchromesh** [comment]
I was able to get the HTTPS support working by following [this tutorial](http://www.sitepoint.com/how-to-use-ssltls-with-node-js/). The OpenSSL commands that worked for me were:

> Generate private key.
> `$ openssl genrsa -des3 -out swankjs.key 1024`
> Generate certificate signing request. Enter `localhost` as the `Common Name`.
> `$ openssl req -new -key swankjs.key -out swankjs.csr`
>  Remove password protection from private key.
> `$ openssl rsa -in swankjs.key -out swankjs.key`
> Generate self-signed certificate.
> `$ openssl x509 -req -days 999 -in swankjs.csr -signkey swankjs.key -out swankjs.crt`

I still get the `unsecure, are you sure?` warning from my browser, but at least it works.

I decided I didn't need non-SSL access so I just changed the `http` protocol to `https` (_etc._ as shown in this pull request).

**Comment by ptillemans** [comment]
Thanks.

**Comment by MC-Escherichia** [comment]
Thanks for the openssl commands, but I had to unmerge this branch as it broke my use case, which is to simply embed the script into a test page. I took a stab at restoring the functionality to this branch but found myself out of my league. I also tried using the openssl commands above and changing the address the script loads from, but to no avail. I've left the branch open here, and will test any future pull requests.

**Pull request merged**
